-- DROP DATABASE
DROP DATABASE IF EXISTS blog_db;

-- CREATE DATABASE
CREATE DATABASE blog_db;

CREATE TABLE user (
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(200) NOT NULL,
    password VARCHAR(200) NOT NULL
)

CREATE TABLE post (
    title VARCHAR(200) NOT NULL,
    content VARCHAR(500) NOT NULL,
)

CREATE TABLE comment (
    content VARCHAR(300) NOT NULL,
)